name: Test GA

env:
  MULTIPLE_FPATH: mock_public/prj_01/README.md mock_public/prj_02/README.md

on:
  workflow_call:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare GITHUB_OUTPUT
        id: files_to_check
        run: |
          echo "fpaths=$(find ./mock_public/ -name "*.md" -print0)" >> "$GITHUB_OUTPUT"
      - name: Test local version with GITHUB_OUTPUT
        uses: ./
        with:
          filepath: ${{ steps.files_to_check.outputs.fpaths }}
